databases:
  - name: good_spot_kansai_app_db
    databaseName: good_spot_kansai_app_db
    user: azuma_yoko_44
    region: singapore

services:
  - type: web
    name: good_spot_kansai_app_db
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: render_app
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false
